spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book-manager
    username: "book-manager"
    password: "1qazxsw2"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    property-naming-strategy: SNAKE_CASE

#  flyway:
#    enabled: true
#    baseline-on-migrate: true
#    baseline-description: Initial
#    # @see org/springframework/boot/autoconfigure/flyway/FlywayProperties.java
#    # locations: "classpath:db/migration"
